### ISSUE TITLE
업데이트 시스템

### ISSUE THREAD

**Issue by DOS0313** [WakGames/Waktaverse-Games-Launcher#3]
## 게임 업데이트 <- 우선
업데이트를 지원하는 게임이 크게 있어보이지는 않지만, 버그 픽스 등 추가 배포가 필요한 상황이 올 수 있음

기능 구현과 관련해서는 Comment로 남겨주세요.

## 런처 업데이트
@NeuroWhAI : exe 셀프 업뎃은 흔한 부분이니 자료 찾으면 꽤 나올 거 같네요.
당장 생각나는 것도 그냥 별도 쉘스크립트 실행하고 런쳐 종료하면 스크립트가 런쳐 exe 업뎃해줄 수 있고..
@kms0219kms : 바로가기 클릭 or exe 실행 -> 런쳐 업뎃 확인 ->

업뎃 있으면 childprocess아닌 dedicated process 실행 -> 업데이트 -> 재실행
업뎃 없으면 게임 업뎃 확인 -> 있으면 다운로드 -> 압축 해제 -> 체크섬 검사 -> 실행

**Comment by DevJeon1358** [comment]
요 작업을 2개로 나누는게 좋지 않을까 싶습니다.
구현 범위가 달라져서요.

1. 런처 자체의 Self Update 구현
2. 게임의 Update 구현
